const services = {
 community:{tag:'CONNECTION / EVERYDAY SETTINGS',title:'Community Integration',intro:'A service page concept about supporting participation and connection in everyday community experiences. The final description and eligibility details need the practice’s review.',points:['What families may want to ask about participation goals','How goals could be discussed with the clinical team','What information to bring to a first conversation']},
 jasper:{tag:'PLAY / SHARED ATTENTION',title:'JASPER Therapy',intro:'A page concept that introduces JASPER in approachable language and provides room for the practice to explain its actual approach, clinician training, and fit.',points:['What the approach means at this practice','How families can participate in the process','Questions to ask about individual goals']},
 myo:{tag:'FUNCTION / QUESTIONS',title:'Myofunctional Therapy',intro:'A page concept for questions about oral function. Scope, suitability, clinical claims, and referrals must be supplied or approved by SSLP’s clinicians.',points:['What concerns the practice evaluates','How the practice decides on next steps','When collaboration with other providers may be discussed']}
};
const esc = value => String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function showService(key,focus=false){const data=services[key];if(!data)return;document.querySelectorAll('[data-service]').forEach(button=>{const active=button.dataset.service===key;button.classList.toggle('selected',active);button.setAttribute('aria-pressed',String(active))});const detail=document.querySelector('#service-detail');detail.innerHTML=`<div><p class="detail-label">${esc(data.tag)}</p><h3>${esc(data.title)}</h3><p>${esc(data.intro)}</p></div><div><p class="detail-label">A FAMILY-FRIENDLY PAGE STRUCTURE</p><ul>${data.points.map(point=>`<li>${esc(point)}</li>`).join('')}</ul><a class="text-link" href="#contact">Ask about this service ↗</a></div>`;if(focus)detail.focus({preventScroll:true});}
document.querySelectorAll('[data-service]').forEach(button=>button.addEventListener('click',()=>showService(button.dataset.service,true)));
showService('community');
const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('#main-nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');nav.classList.toggle('open',open)});nav.addEventListener('click',event=>{if(event.target.closest('a')){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');nav.classList.remove('open')}});
document.querySelector('#contact-form').addEventListener('input',event=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement)event.target.setCustomValidity('');});
document.querySelector('#contact-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const name=form.elements.name.value.trim();const email=form.elements.email.value.trim();const topic=form.elements.topic.value;const message=form.elements.message.value.trim();if(!name||!message){const field=!name?form.elements.name:form.elements.message;field.setCustomValidity('Please enter more than spaces.');field.reportValidity();return;}const feedback=document.querySelector('#contact-feedback');feedback.textContent=`Preview ready, ${name.split(/\s+/)[0]}. This concept does not send or save your message.`;feedback.classList.add('success');const preview=document.querySelector('#message-preview');preview.hidden=false;preview.innerHTML=`<strong>Message preview · not sent</strong><p><b>From:</b> ${esc(name)} (${esc(email)})</p><p><b>Topic:</b> ${esc(topic)}</p><p>${esc(message).replaceAll('\n','<br>')}</p>`;preview.scrollIntoView({block:'nearest',behavior:'smooth'});});
