const $ = (selector, root = document) => root.querySelector(selector);
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const today = new Date(); today.setHours(12,0,0,0);
const iso = (date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const offset = (days) => { const date = new Date(today); date.setDate(today.getDate()+days); return iso(date); };
const employees = [
  {name:'Alex Morgan',initials:'AM',role:'Product Designer',team:'Design',tone:'gold',balance:13},
  {name:'Maya Chen',initials:'MC',role:'Lead Engineer',team:'Engineering',tone:'violet',balance:17},
  {name:'Jordan Lee',initials:'JL',role:'Brand Strategist',team:'Creative',tone:'green',balance:11},
  {name:'Sofia Patel',initials:'SP',role:'Operations Lead',team:'Operations',tone:'blue',balance:16},
  {name:'Noah Williams',initials:'NW',role:'Frontend Engineer',team:'Engineering',tone:'gold',balance:9},
  {name:'Avery Brooks',initials:'AB',role:'Content Lead',team:'Creative',tone:'violet',balance:14}
];
const initialRequests = [
  {id:1,person:'Maya Chen',type:'Annual leave',start:offset(4),end:offset(6),reason:'Family visit',status:'Pending'},
  {id:2,person:'Jordan Lee',type:'Casual leave',start:offset(9),end:offset(9),reason:'Personal appointment',status:'Pending'},
  {id:3,person:'Sofia Patel',type:'Annual leave',start:offset(12),end:offset(14),reason:'Time away',status:'Pending'},
  {id:4,person:'Noah Williams',type:'Work from home',start:offset(-4),end:offset(-4),reason:'',status:'Approved'},
  {id:5,person:'Alex Morgan',type:'Annual leave',start:offset(-12),end:offset(-10),reason:'',status:'Approved'}
];
let requests;
try { requests = JSON.parse(localStorage.getItem('daylight-demo-requests')) || initialRequests; if (!Array.isArray(requests)) requests = initialRequests; } catch { requests = initialRequests; }
let view = 'overview'; let filter = 'All'; let month = new Date(today.getFullYear(), today.getMonth(), 1);
const persist = () => localStorage.setItem('daylight-demo-requests', JSON.stringify(requests));
const niceDate = (value, options = {month:'short',day:'numeric'}) => new Date(`${value}T12:00:00`).toLocaleDateString('en-US',options);
const range = (item) => item.start === item.end ? niceDate(item.start) : `${niceDate(item.start)}–${niceDate(item.end)}`;
const avatar = (name) => { const person = employees.find(p=>p.name===name); return `<span class="person-avatar ${person?.tone||'green'}">${esc(person?.initials || name.split(' ').map(s=>s[0]).join(''))}</span>`; };
const status = (item) => `<span class="status ${item.status.toLowerCase()}">${esc(item.status)}</span>`;
const pageHead = (eyebrow,title,desc,button=true) => `<div class="page-head"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${desc}</p></div>${button?'<button class="primary" data-action="new-request">+ &nbsp; New request</button>':''}</div>`;
const rows = (items, actions=false) => items.map(item=>`<tr><td><span class="person">${avatar(item.person)}${esc(item.person)}</span></td><td>${esc(item.type)}</td><td class="muted">${esc(range(item))}</td><td>${status(item)}</td>${actions?`<td>${item.status==='Pending'?`<div class="table-actions"><button class="mini-button" data-id="${item.id}" data-action="approve">Approve</button><button class="mini-button reject" data-id="${item.id}" data-action="reject">Reject</button></div>`:'—'}</td>`:''}</tr>`).join('');
const table = (items, actions=false) => `<div class="table-scroll"><table class="requests-table"><thead><tr><th>TEAM MEMBER</th><th>TYPE</th><th>DATES</th><th>STATUS</th>${actions?'<th>ACTION</th>':''}</tr></thead><tbody>${rows(items,actions)||`<tr><td colspan="${actions?5:4}" class="empty">No requests in this view.</td></tr>`}</tbody></table></div>`;
function overview(){
  const pending = requests.filter(r=>r.status==='Pending').length;
  const approved = requests.filter(r=>r.status==='Approved').length;
  const upcoming = requests.filter(r=>r.status==='Approved' && r.start>=iso(today)).length;
  return `${pageHead('MONDAY IS BETTER WITH A PLAN','A clearer view of time away.','Here’s what is happening across your team today.')}
  <div class="stats"><div class="stat"><div class="stat-top"><span>Team members</span><span class="stat-icon">♧</span></div><div class="stat-value">${employees.length}</div><div class="stat-note"><strong>● Active</strong> across 4 teams</div></div><div class="stat"><div class="stat-top"><span>Pending requests</span><span class="stat-icon">◷</span></div><div class="stat-value">${pending}</div><div class="stat-note">Waiting for a decision</div></div><div class="stat"><div class="stat-top"><span>Approved leaves</span><span class="stat-icon">✓</span></div><div class="stat-value">${approved}</div><div class="stat-note">${upcoming} coming up</div></div><div class="stat"><div class="stat-top"><span>My annual balance</span><span class="stat-icon">✳</span></div><div class="stat-value">13<span style="font-size:.9rem;letter-spacing:0"> days</span></div><div class="stat-note">From 20 allocated days</div></div></div>
  <div class="content-grid"><div class="stack"><section class="panel"><div class="panel-head"><div><h2>Requests needing attention</h2><p>Keep your people and plans moving.</p></div><button class="text-button" data-view="requests">View all ↗</button></div>${table(requests.filter(r=>r.status==='Pending').slice(0,4),true)}</section><section class="panel"><div class="panel-head"><div><h2>Time away at a glance</h2><p>A sample look at recent activity.</p></div><span class="muted" style="font-size:.65rem">LAST 6 MONTHS</span></div><div class="chart">${[35,52,44,68,60,78].map((h,i)=>`<div class="bar-col"><div class="bar-track"><span class="bar" style="--h:${Math.max(20,h-22)}%"></span><span class="bar dark" style="--h:${h}%"></span></div><span>${['APR','MAY','JUN','JUL','AUG','SEP'][i]}</span></div>`).join('')}</div><div class="legend"><span>Approved</span><span>Requested</span></div></section></div><div class="stack"><section class="balance-card"><h2>Your leave balance</h2><strong>13 <small>/ 20 days</small></strong><p>A little room to recharge goes a long way.</p><div class="balance-line"><i></i></div><div class="balance-footer"><span>7 used</span><span>13 available</span></div></section><section class="panel"><div class="panel-head"><div><h2>Team notes</h2><p>Everything in one place.</p></div></div><div class="activity"><div class="activity-item"><span class="activity-dot"></span><div><strong>Review pending requests</strong><small>${pending} teammate${pending===1?'':'s'} waiting for approval</small></div></div><div class="activity-item"><span class="activity-dot"></span><div><strong>Next team holiday</strong><small>${niceDate(offset(17),{month:'long',day:'numeric'})} · sample schedule</small></div></div><div class="activity-item"><span class="activity-dot"></span><div><strong>Plan ahead together</strong><small>See your team’s leave calendar</small></div></div></div></section></div></div>`;
}
function requestView(){ const items = requests.filter(r=>filter==='All'||r.status===filter); return `${pageHead('REQUEST CENTER','Time off, made simple.','Review every request with the context you need.')}<section class="panel"><div class="filters">${['All','Pending','Approved','Rejected'].map(f=>`<button class="filter ${f===filter?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div>${table(items,true)}</section>`; }
function teamView(){ return `${pageHead('PEOPLE FIRST','The people behind the plan.','A sample team directory with leave balances.')}<div class="filters"><label for="team-search" class="visually-hidden">Search people</label><input id="team-search" class="search" placeholder="Search people or teams" type="search"></div><div class="team-grid" id="team-grid">${teamCards(employees)}</div>`; }
function teamCards(items){return items.map(p=>`<article class="team-card">${avatar(p.name)}<h3>${esc(p.name)}</h3><p>${esc(p.role)} · ${esc(p.team)}</p><footer>${p.balance} annual days available</footer></article>`).join('')||'<p class="empty">No people match that search.</p>';}
function calendarView(){ const first = new Date(month.getFullYear(),month.getMonth(),1); const count = new Date(month.getFullYear(),month.getMonth()+1,0).getDate(); const start = first.getDay(); const cells=[]; for(let n=0;n<start;n++) cells.push('<div class="day faded" aria-hidden="true"></div>'); for(let n=1;n<=count;n++){const date=iso(new Date(month.getFullYear(),month.getMonth(),n)); const onLeave=requests.filter(r=>r.status==='Approved'&&r.start<=date&&r.end>=date);cells.push(`<div class="day ${date===iso(today)?'today':''}">${n}${onLeave.map(r=>`<small>${esc(r.person.split(' ')[0])} · Away</small>`).join('')}${n===15?'<small class="holiday">Team holiday</small>':''}</div>`);} return `${pageHead('SEE THE WHOLE PICTURE','A calendar with context.','Spot busy weeks and give your team room to plan.')}<section class="panel"><div class="panel-head"><div><h2>${month.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</h2><p>Approved leave and sample holidays</p></div><div class="table-actions"><button class="mini-button" data-action="prev-month" aria-label="Previous month">←</button><button class="mini-button" data-action="next-month" aria-label="Next month">→</button></div></div><div class="calendar">${['SUN','MON','TUE','WED','THU','FRI','SAT'].map(d=>`<div class="weekday">${d}</div>`).join('')}${cells.join('')}</div></section>`; }
function reportView(){ return `${pageHead('USEFUL AT A GLANCE','Reports without the hunt.','A small set of exports ready for your workflow.',false)}<div class="report-card"><div><strong>Leave request history</strong><p>All sample requests, dates, types, and statuses.</p></div><button class="secondary" data-action="export-requests">Download CSV ↓</button></div><div class="report-card"><div><strong>Team balance summary</strong><p>Remaining annual days by team member.</p></div><button class="secondary" data-action="export-team">Download CSV ↓</button></div><section class="panel full"><div class="panel-head"><div><h2>What this prototype demonstrates</h2><p>Sample workflows, stored in your browser only.</p></div></div><p class="muted" style="font-size:.76rem;line-height:1.8">Requests can be added, approved, rejected, filtered, and exported. Production authentication, permissions, database rules, holiday policies, and notifications would require the full commissioned project.</p></section>`; }
function render(){ const titles={overview:'Overview',requests:'Requests',team:'Team',calendar:'Calendar',reports:'Reports'}; $('#breadcrumb-current').textContent=titles[view]; $('#main').innerHTML=({overview,requests:requestView,team:teamView,calendar:calendarView,reports:reportView})[view](); document.querySelectorAll('.nav-item').forEach(button=>button.classList.toggle('active',button.dataset.view===view)); $('#pending-badge').textContent=requests.filter(r=>r.status==='Pending').length; }
const dialog=$('#request-dialog');
function openDialog(){ $('#request-form').reset(); $('#start-date').min=iso(today); $('#end-date').min=iso(today); $('#start-date').value=offset(1); $('#end-date').value=offset(1); $('#form-error').textContent=''; dialog.showModal(); }
function exportCsv(filename,lines){const quote=s=>`"${String(s??'').replaceAll('"','""')}"`; const content=lines.map(row=>row.map(quote).join(',')).join('\r\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return; if(button.dataset.view){view=button.dataset.view;render();return;} const action=button.dataset.action;if(action==='new-request')openDialog();if(action==='approve'||action==='reject'){const item=requests.find(r=>r.id===Number(button.dataset.id));if(item){item.status=action==='approve'?'Approved':'Rejected';persist();render();}}if(action==='prev-month'||action==='next-month'){month=new Date(month.getFullYear(),month.getMonth()+(action==='prev-month'?-1:1),1);render();}if(action==='export-requests')exportCsv('daylight-requests.csv',[['Employee','Type','Start','End','Status'],...requests.map(r=>[r.person,r.type,r.start,r.end,r.status])]);if(action==='export-team')exportCsv('daylight-team.csv',[['Employee','Team','Annual days available'],...employees.map(p=>[p.name,p.team,p.balance])]);if(button.dataset.filter){filter=button.dataset.filter;render();}});
document.addEventListener('input',event=>{if(event.target.id==='team-search'){const q=event.target.value.trim().toLowerCase();$('#team-grid').innerHTML=teamCards(employees.filter(p=>`${p.name} ${p.team} ${p.role}`.toLowerCase().includes(q)));}});
$('#today-button').addEventListener('click',()=>{view='overview';render();});
$('#close-dialog').addEventListener('click',()=>dialog.close());$('#cancel-dialog').addEventListener('click',()=>dialog.close());
$('#request-form').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget);const start=form.get('start'),end=form.get('end');if(end<start){$('#form-error').textContent='End date must be on or after the start date.';return;}requests.unshift({id:Date.now(),person:'Alex Morgan',type:form.get('type'),start,end,reason:String(form.get('reason')||'').slice(0,500),status:'Pending'});persist();dialog.close();view='requests';filter='All';render();});
render();
